import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tier",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header>
          <div className="topo-esquerdo">
            <img src="/image/logo.png" alt="" />
          </div>
          <div className="topo-direito">
            <ul>
              <li>
                <Link className="link" href={"/"}>Inicio</Link>
              </li>
              
              <li>
               <Link className="link" href={"/sobre"}>Sobre Nós</Link>
              </li>
              <li>
                PODCAST
              </li>
              <li>
                CAREERS
              </li>
              <li><Link href={"/login"} ><button className="btn-header">Login</button></Link></li>
              <li><Link href={"/cadastro"} ><button className="btn-header">Cadastrar-se</button></Link></li>
            </ul>

          </div>

        </header>
        {children}
        <footer className="footer">
          <div className="footer-container">

            <div className="footer-logo">
                <h2>Tier</h2>
                <img src="/image/logo.png" alt="" />
            </div>


            <div className="footer-contato">
              <h3>Contato</h3>
              <p>Telefone: (11) 93056-9806</p>
            </div>


            <div className="footer-endereco">
              <h3>Endereço</h3>
              <p>Rua das Indústrias, 245</p>
              <p>Centro Empresarial</p>
              <p>São Paulo - SP, 09000-000</p>
            </div>

          </div>
        </footer>
      </body>
    </html>
  );
}
